"""Constantes de configuración para la app Streamlit (spec 09)."""

STREAMLIT_PAGE_TITLE = "Puts Screener"
STREAMLIT_PAGE_ICON = "📉"

# Chart
STREAMLIT_DEFAULT_CHART_MONTHS = 12
STREAMLIT_CHART_MONTH_OPTIONS = (3, 6, 12, 24)
STREAMLIT_CHART_HEIGHT_PX = 600

# Colores
STREAMLIT_ZONE_BAND_COLOR = "rgba(0, 180, 0, 0.18)"
STREAMLIT_ZONE_BAND_OPACITY = 0.18
STREAMLIT_MA_COLORS = {
    "SMA200W": "#FF6B35",
    "EMA200D": "#004E89",
    "SMA50D": "#9B59B6",
}
STREAMLIT_STRIKE_COLORS = {
    "aggressive": "#E74C3C",
    "natural": "#F39C12",
    "conservative": "#27AE60",
}
STREAMLIT_SPOT_LINE_COLOR = "#555"
STREAMLIT_CANDLE_INCREASING = "#26A69A"
STREAMLIT_CANDLE_DECREASING = "#EF5350"

# Cache
STREAMLIT_DB_QUERY_CACHE_TTL_SECONDS = 300
STREAMLIT_OHLCV_CACHE_TTL_SECONDS = 300

# Sidebar
STREAMLIT_SIDEBAR_RUN_LIMIT = 30
